---
functional:
  - Возможность авторизации через Github
  - Возможность авторизации и голосового чата через Discord
  - Ведение рейтинга игроков по неделе/месяцу/всего и отображение на главной странице. Возможность сортировки по рейтингу, количеству игр и т.д.
  - Возможность просмотра истории баттлов
  - Уведомление о начале баттла
  - Возможность организации турниров и турнирной сетки
  - Возможность переподключения участника к баттлу
  - После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
  - В истории есть иконка напротив никнейма, указывающая на победителя баттла
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов
  - Игроки могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Можно выбрать игру по уровню сложности
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры в режиме online
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи
  - Редактор для ввода кода выглядит как проигрыватель
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователи могут просматривать список рейтинга
  - Codebattle это SPA приложение, которое не перезагружает страницу
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла
